### ISSUE TITLE
inference error of state_dict

### ISSUE THREAD

**Issue by jingpengw** [nicholasturner1/PyTorchUtils#2]
@nicholasturner1 any idea?
```
model_file_name = '/import/w4_wt_focused_760k_pytorch/w4_wt_focused_760k.py'  
net_file_name = '/import/w4_wt_focused_760k_pytorch/w4_wt_focused_760k.chkpt' 
```

```
Traceback (most recent call last):                                                             
  File "pytorch.py", line 27, in <module>                                                      
    engine = PyTorchEngine(model_file_name, net_file_name)                                     
  File "pytorch.py", line 11, in __init__                                                      
    self.net.load_state_dict(torch.load(net_file_name))                                        
  File "/usr/people/jingpeng/lib/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.
py", line 522, in load_state_dict                                                              
    .format(name))                                                                             
KeyError: 'unexpected key "module.inputconv.conv.conv.weight" in state_dict'                   
```

**Comment by nicholasturner1** [comment]
(Corresponded in person, but recording here)
At this point, models need to be wrapped in DataParallel objects. This should be changed soon
